# Generated by Django 4.0.4 on 2022-07-01 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploader',
            name='is_save',
        ),
        migrations.RemoveField(
            model_name='imageuploader',
            name='name',
        ),
        migrations.AddField(
            model_name='imageuploader',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
