# Generated by Django 4.0.4 on 2022-07-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_imageuploader_is_save_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_converter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
