# Generated by Django 4.0.4 on 2022-07-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_pdfuploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfuploader',
            name='pdf_image',
            field=models.ImageField(default=0, upload_to='pdf_image/'),
            preserve_default=False,
        ),
    ]
